# cloud-config
resize_rootfs: true

write_files:
- content: |
    vm_number=${vm_number}
    vm_name=${vm_name}
    vm_names="${vm_names}"
    vm_ip=${vm_ip}
    vm_ips="${vm_ips}"
    vm_ip_network=${vm_ip_network}
    vm_swap_size="${vm_swap_size}"
    vm_os_registration=${vm_os_registration}
    vm_reg_code="${vm_reg_code}"
    vm_reg_email="${vm_reg_email}"
    vm_product_id="${vm_product_id}"
    vm_saptune_solution="${vm_saptune_solution}"
    vm_sap_instance="${vm_sap_instance}"
    admin_password="${admin_password}"
    sap_media_stg_enabled=${sap_media_stg_enabled}
    sap_media_stg_type="${sap_media_stg_type}"
    sap_media_stg_account="${sap_media_stg_account}"
    sap_media_local_mount="${sap_media_local_mount}"
    sap_media_stg_remote_path="${sap_media_stg_remote_path}"
    sap_media_stg_access_key="${sap_media_stg_access_key}"
    sap_media_local_add_fstab="${sap_media_local_add_fstab}"
    sap_media_pe_private_ip="${sap_media_pe_private_ip}"
    data_stg_enabled=${data_stg_enabled}
    data_stg_account="${data_stg_account}"
    data_stg_remote_path="${data_stg_remote_path}"
    data_stg_remote_clean="${data_stg_remote_clean}"
    data_stg_local_add_fstab="${data_stg_local_add_fstab}"
    data_stg_pe_private_ip="${data_stg_pe_private_ip}"
    saptrans_stg_enabled=${saptrans_stg_enabled}
    saptrans_stg_type="${saptrans_stg_type}"
    saptrans_stg_account="${saptrans_stg_account}"
    saptrans_stg_remote_path="${saptrans_stg_remote_path}"
    saptrans_stg_remote_clean="${saptrans_stg_remote_clean}"
    saptrans_stg_local_add_fstab="${saptrans_stg_local_add_fstab}"
    saptrans_stg_pe_private_ip="${saptrans_stg_pe_private_ip}"
    enable_monitoring=${enable_monitoring}
    cluster_install=${cluster_install}
    cluster_unicast=${cluster_unicast}
    cluster_password=${cluster_password}
    subscription_id=${subscription_id}
    resource_group=${resource_group}
    tenant_id=${tenant_id}
    login_id=${login_id}
    app_password=${app_password}
    sap_ascs_instance_sid=${sap_ascs_instance_sid}
    sap_ascs_instance_id=${sap_ascs_instance_id}
    sap_ascs_root_user=${sap_ascs_root_user}
    sap_ascs_root_password=${sap_ascs_root_password}
    sap_ascs_vip_address=${sap_ascs_vip_address}
    sap_ascs_vip_hostname=${sap_ascs_vip_hostname}
    sap_ers_instance_sid=${sap_ers_instance_sid}
    sap_ers_instance_id=${sap_ers_instance_id}
    sap_ers_root_user=${sap_ers_root_user}
    sap_ers_root_password=${sap_ers_root_password}
    sap_ers_vip_address=${sap_ers_vip_address}
    sap_ers_vip_hostname=${sap_ers_vip_hostname}
    sid_adm_password=${sid_adm_password}
    sap_adm_password=${sap_adm_password}
    master_password=${master_password}
    sapmnt_path=${sapmnt_path}
    sidadm_user_uid=${sidadm_user_uid}
    sidadm_user_gid=${sidadm_user_gid}
    sapmnt_inst_media=${sapmnt_inst_media}
    swpm_folder=${swpm_folder}
    sapexe_folder=${sapexe_folder}
    additional_dvds=${additional_dvds}
    sap_hana_host=${sap_hana_host}
    sap_hana_ip=${sap_hana_ip}
    sap_hana_sid=${sap_hana_sid}
    sap_hana_instance=${sap_hana_instance}
    sap_hana_password=${sap_hana_password}
  path: /run/scripts/vars
  owner: root:root
  permissions: "0640"
  append: false
- encoding: gzip+base64
  content: |
    H4sICMkoaWICA3NldHVwX3NhcF9uZXR3ZWF2ZXJfaGEuc2gA7T1pdxs3kp+XvwKhlciK3LwkyjEnzFix
    ZUfzbMlPsrNv13L6NbtBEqO+0kBLoh3+96kC0Ce7ecmedWbjDzYJFKoKhboAFOEH37RHzG+PLD5tNB6Q
    C+qwiNqCYAMJYhHGovHq/KX54vTVybDZjoJAtG03iB2D+UwYnIo4bLnBpNmgd9QmP5GdBJr0fvquizgv
    hRUJIphHG9SeBqSZNQzIzkPHEnSviYCvAsshgkaRNQ4ij9xYEdcjsIf5k2Ins0Yu5aTVajUbt1PmUvKe
    fEOMMWlHsd/mdsRCwduIhXz4G3ECwl1KQ9LFzz5t8CCObLoILFnGaRF+a4Uk5kj4+GMcUeLQGwZDRm5g
    X2vOTnzgAiEWgF8xP74jxxPqC8Ujpw4xGGny9gVVxJ8zft2SGOglDB/6tT2zdpO0qbDbt5aFGFt24I/r
    MOKIS/aRvv552Knt2fl045nItMmhYV6Nf8YF9WzhkohyuWhJN6cRiqJBQFjPIgpLSCZRgDKzQhilhSN7
    UCIgMMsF6dCIWL6jQPXK2Z4z3Hk4oQLllMex14ioGO78vcHGsLA7n+DbnBg+JR1cTjGlfoOoAZYDYpgA
    CGeO5Xgm0jEnzJkn3IxZnlHJhuTIneVE+Nu70+fm69Ozq4et76/22vob6Xc67YkWDug581sOHfMGIuHI
    eAQqdTco0o6RthwRWpzfOuQPYseCGM4A1LO71wDjoswZdrudToM5ZujGfNhpgF4r3pgPc5EE5qirME38
    4gXAaQwG81ANJ/tEj93b0/BzAE3wAZz+CIDdvb2GVPqCtDVzTWAe1MDiNjeZD+vs2xSUwjHd4BZwwqya
    6VosAQS8ctVrsM1BCCIizffHxv9+aMK/lvHxAyBetro4J7m4npz5ooyrV32NCaFKoJ2/uzwhv4KgWeA3
    zi/NX08uzNfH/zi/gMlIzfDJLmgGNF+enp8Nm0o3jNb37atuO9xVaxxwI6IuhUXZS3C8ePfqVSUK8/R5
    gqVZh0O64QkD04uIssBESGCxATcj2RmBZQX+nAxBqjHNCQ3n9CzwffTihmEDUj8Oy+2RwgaoTDtwKEiS
    Zi3Us5g71yK6oGMw/il4gDDgjY+zMAS2IjrGPuWglBRBPWNwxwmreWECk0PS7PaadVyG6JoNhcEIY3Co
    tiGDTLvba9/9cGQeHTaoy+n641IGcCXmCQ41o3chhpxEtMpTyTb0VKFlX4OL085JTxfWENyS4eLoU1Qo
    11WTTqHRdi+P35DjMAQm5NLkBoNBG2huApbUR6dkov/E5bVCw78lU8vkKLvCiKk1gmCLCx0aGPJi10J4
    /3ax+QoEwy1XGB4E5QAogHMT6LOl5zekywYeqZ99UUNCg4PZgMxi1DbDVoKFuYQzMQ38AyOMAo/CksXc
    tF2mnIawp3K4SgN8UF+IFWxiWBj2GusqQGGuipzCYDAH6DAxK7Z6E08Agx4kJDRRhgocB9VIDqqwKHWQ
    WYcLFpXlFA0wBN/yKB8+lEYhP8/3sJmFSSN8giZwTwxX23JN58aRfaWmubToMypug+ia2EGE+RV0c8yx
    wEHAek2FCPmg3b69vW3hgkD09do8DsMgEu3rUdsJ7PbfIWB04E/3ycEP3SS+Ti1/glrrp9hxJWLlG8pZ
    x2/PXp2/e26enbx9dn724vQlrM3Z8cuToQ54db27fnC1iyEQ11w6K7AcRait6bbZ2B5PDFCUTiOyE2bA
    oYFocfLHjszepgEImfmotYpBESiE2MEbLvUhK3mQyPv90w9zGRMfPiRs2PkbYT/uAAj8u79P9vZ0ZFSC
    SBbk/Q77MCfwJ1s22dQkP/2UJyVjITD2kt1QYjk3li/ALmRKikz54BJJN+d1EZNU4hzeLlDK1Fnllj1P
    K9XrIAZb+QVESF5DSm3pBYNm6WXQVWSdaqEkNR26PGw2Q2qGEbsBZwVzgzmgEeVNSKq0yadWRIeFgVxM
    TMu2kYd5awyZMShURFu3zHeCW96CBWomJlSLo0Qc56XlUaQjZqESTZN7ozx3Mhl3CvAy6TI9yRf5QL77
    jnjXsN9AR14HliFqKt3zRnZEpXFbLm+WsFSA4NqoBhTEsApLu1Z2CNTEpGqc7C0ANMOWVwDwh+Bzf/zx
    5PwF7oIKYDJbRK0Z1lFqyFwsiJwqCMq5eU1n8wbgVpSmmAwedTplOtgJDWYQSg8zbN5glnrQ6jzKTXdY
    HPQIZAfCduiw8/jx40fYlvuqAhXzg6ZEvqACaq3A5ZljiIujinwE/yjtb4Ogc/o2X5B7RL0A9A1CzHRO
    6jWH2GzMiZp7MtWciUtGNGE5YplyAW/KEDJoCNWSwGbsXmkcS/g2ghLPcghuTvAvzccKI/PH/OagWRAv
    NJUXHBcrnddi/+EjSBQCXFhMfIddWGV7CF692dDsfDbbTSUKTJCiOAe1Zrdc0MvFm5vsvLGlviYxpcDt
    dswuUWJf6XCe4SodXqnB6Tovk/V23Cc6vZHIQYFUDHw2pfa1DHXqTCmIGGTKEPbPXlwSyZeOim9gbwGp
    l46LkIhbBDp1WATKwgvBb8PfbfUli5UIK9neMFSm47aLknVkceKbWFvezGBelXaF7Y0VZrQwnXzbovFI
    UotLV3XcQn8vbMh1Xxm33GSmpmRYOiGTWZNai1ze1MF0LG9u7wsywDX2fFF7iiBFlChm5MFWdrz24Pb3
    VQRjHsHHujHYsoLoagTbEKbR/ejC+G3IgmLeiyyMl2RlHEnP3BIPMCOwc41tgQekge/O0B3obFtr14aq
    8832yrNoZyuGV5PcVH0qyK5GsQ3pBQXamDJg2IbwggptTBgPbbUKxbkAKH2hdsn6+D2KYIcoQTB+YGTJ
    VC05lEF31Wrmo1IaayrVkmAwKBwPZRFKnWSrzkJcS4jJoKUFpvWpvVofPzUKclo1UO8CLCEiss/WAZ+n
    PIHkEb4tIsvn9RwUwMr0yp2L2Gtd8OX/XK4mumx0HS8rxmzA4vHls8uqzqUrdh+sG09pOa4NpnpyofGA
    qX+uidbi3HiayzDNs2OWNGtUuWV21uKLQlJZOGb5k6eO5Uxs9b5GcpvcWBn2wganKo9s5nYje1n+Z+vs
    v5Qd1uycKhPUeuevb2lWhfLVznXdHdbnZHp1YFzTRX59zMtM5p7e8+ubFSZJ9/KT601JpjIqk1kjWGvA
    NSPbutDLg8a6WOp9snZ4G+9V7+0KVJq50h9UHVZ8AWZXuwDN71p+4KtgWpr+ulwvs/+vYjZo8utOpt7u
    F6ZCClc/mHTgjkUm2SuSEwVUvgSSrdtkKIWxW18D1ZLfMlMpoNwiWynuOTZNTKqYyN1ciYnVrLyyqDyy
    XpRuuT1/5rYkQSntxdaOjtmNRcJlLfUaIvqaoAJ5ch2xEBHUXm/hlmI9ea6+B/hcQk3OHErTrvI8dSfn
    6wsTsCpJFs+9LX9CSUgjj3Eub/rB9tXBQek0fMUVc6dwxQxLfesT44KsLG8aqLq3e+cEX4Lisj3dl6CH
    OZJeF10cQWWtTHY6REM3mHnUFwuHPRKO+jcsCnwvrePM3fOqy2SAaqvKm5aDzKjiSXmRivWyfABTw1qP
    gVQ2AzKV6EaOSr7LSaAxyNakrIe3YR4ClASvfbMjJRgbMte1ovLdd9ZTYDFrbosgbHGXNxJmdr/fTXjS
    JUD6G5ZwUAtUW9F+QN4oiiizN5ZNPeuaRuSZHpO/+M6T0zglSf15oA6F1ReCWg4N+M+ATK2MB6wtHpQs
    AZpvsfbICSYDbbVY9zUgPBgLaJRtqkJ3QNrwoZ2AS4SAeGxhl6xSIST2mW1xSUXTNXWTosSECbM1kRNm
    ueyjrFgZkAMc64twQMIgcFvwqRVEE+ktATJAtTGpLItzELX6aGadUs2DKOAz31bTEOBevIH2WiK4ppIK
    /Mk3gRuSHsdjgpsjCpxRMAbOTVA1nEQ3gf5nwGD8UfIVu6nPYw44jzKcnnVnglg51q4NSC9pzqSUXmaP
    IFkAbYBQHekFYaGpK3zUgc7vcRDF6QToXQjOjTrmDUyLJ2sYeyNVnSondBuYeOY/kIf+6bKbSQnEAANa
    uXGOd9OcT6/pjCtaBXBwCcwvAie1UHoyYRSARxbgdBNWucBVmRrpco2tLLAmnVgSFMRCLkkmUzuOIvAH
    BpbUwaIOZPaiu/3AUCIxwsBl9gz4YxNIjWizhNqylUo1g/FY9UXcNh06tmJXpFymVXxcMDy4hlXD5c6W
    kk1UuZchplioGbgwk37WP7aYi5Vv6USOdFcQLtBagEHyoK2OEVLfySaqncLx8+enb0/Pz45fmc9/fQ7J
    GrShh3BuHCzIay6UwmFJV1MWbj1IcxflcCDPv8Fle6Bq8x+QvZLXOUs8EpE/Oaj1Oannkl4n/TaQPkBW
    bppJ0Wa6auDfRazyUZAgTzQkLSoD51PhjHIA3RJANwXAoATpgIWZ8yD/HevQ8kAyct2AbWkmUui0A0fI
    JCE3CmNo1aCkPT8mVyat5hcz6aLKRdWyb7LYN1F9GIaxLTM/CVZom6vi0kW4Upvc/lkl49/5VGqSLhNv
    mE1IzwbkhbZSfht64KJdh0rPlPuqydM7mu/PN8wzdZC2k8KpKgNEFftYrus71MHtUVGPk6C5qOBKNaZW
    FgPeKh3DmknhmjeWGyf6deO1IHSLmTmaSVd51HvSPewnppf1grrizxx8JwE8ALDHvR80IOh4i4U3hy1h
    hyZaMEzLCwGsIznxLUUNVWFQ0khVL8acQnt6v5TkUcVRunFe8sE5kMLqrh8VMSSkkk24XbC5zFrzE6ox
    ksLkam7RFudZfT0DrhByOWU+ecC0tQC2oPUpaF46kkPYbMQ+MBS4sYoH6pc5peYEHMKYE9vCVPMCwKwh
    h9HMz0lhK61chYi7S0Vc5VJKEi5k9EsEXHkvVCFfhFtPvCnkVyDdJDiGoTvT1fIYwNJQhN4hnxknRz6F
    gvlmWjFvBHWd/fwWuxAP0YkVqbQkIw3DMErkIXtlk//qdXo9o3No9Dqk0x/0jgadbuuo2398cHD4uEP2
    ZTa6v79fGlse9njQP2w96Rw8Puj3u8mwp0+J0e8/6vXJPv7TJU+fNkgDk6CwIDjz06dUUaRCkvlcegOV
    5rei2B80jNL2pIU/Ooxhew6YIC0TUeBqIAQbx75OsXYvgdxu1iOVFgiiz2nBl5bcWD7cA5oZEJOZdY6t
    Qm+mgognyzpKofAPnWM9zEBK4S0jahBw76IlS8lz03CpPxFTSNMb+3r6cr+0TAgJ5IIE9lfPf3/J7Pe/
    xNz1NCP6e8yibOuRW2YzSd0qdKRamfTvE7+8Ul0qQn/pViqI/0gVQy/WPTyUbqx72Mn7MSsS/ye6B3S1
    zAtijvEnUVLM/991cg0B/al0da2QWaOTX14X/9I28R+pT5jOqizWMEbMt6LZqvPq7AymlIQuSUzVCX19
    zpx4Z9xHfcmsuUwnlzcvdBUy584R6XYHh51B94dWr/+kf3DY7x/mMufy6MLA3qDTGfSftPq9x/3e0dEP
    R7nc+aD3qNsl++ofjDmfvsXbN6la9E5EuN+OYK0EXmszTkApmE8d8i2sfCx/6ZxsaJm8kdjKE2hEeKRq
    Ipac/WRtSpsllYItf/rWkKt5TWeP5PkHHg5W8t9ignoc7OTbdDhBrDAS2SRN+Cwx/MGFvKCZz5s5QKBD
    fQdJfTuvs+byTBK42mns32cS++tNYb9qArjQeOo6ll8a66Uqg/vZa1lLlxrFujaLMvk3mKwmU2GxSc9W
    BqsHl+21O+g8bvUf99FeD/qf117V+chf5vqnNlcbf2eA4TWMArmS6W8NTHrHuOBf0Hy1zi6zD2W8L6lP
    I/x9jo7IpQcEkivys5xNk1/YZEqObyzmWiPmMjFbuDZ/dvqz/AnFmuMXbtWLl8hs1FJckUYYMY8J/M0+
    3pTJVy7MusNdc1kdmnoMwh2RKywXkcrACb62MDzqdeoGSdggTM60k9uyYa/D1c0pKMqw28GCAjEddpZw
    u3BQatbXmS1jtVsz5n6csnA7oZ6+wWuoXoFRFg5r7rcWmMwxxvMc13G3iRCXsla+RNuWM3qHywLxeSvp
    SaLqd0XOIHt2xZDXKgEXKfqn26OHOalnvNIZddL5dDudHBD8tQKmQjiqDxi3CFCZUGHAZokO5d6IOsul
    tclqbiqqjXF/TXJCLrdacXC8p8neUjNDlV/n5GqHOcP7YDfyyGpn2stEctQheM0KXn+YvCWXN8aE07Ps
    kYzNGDLrLgIVGfhz+fb44q355uJcPWUo4T1frKgnbOvw3f6sTDVTro7fvT1/ffz29Jl5cfLsHFLfoaxC
    yalIRQHIEOs7ypUdKOKKYpBhl4BCQeorZqB6tcq1iY1sqFkboP43qNUG3Jg1N5/p4q2pVQskS0r1GVhq
    5nmq06nTS0Q8lJXWUrVyigG7F/X44iQK7xHA7pM/pAi2dnkZhu1TwxTHvcL5gjA3jkFb5zoVYtxu+JYJ
    a50AN8DRsAMsl5Z7EPi4dCZ+YI4CAdsl9ImD+0h8W81vpLzCh6W8op8K8ARHBNj7OZQ9hm1WT848in0u
    adZQJ/R30m0EkQPbMPh7OaMsgjRK3SPIH/+ch6rKaXAvngc5D721hg5k1sVnHriwiNkQEFTdpq67uKBe
    gI+6xWIKvu0jdfDpLC73o4336nVgfMO4xfm0XQaSBdXyvYtlUPqBYFmJkp7Vl1/kK3SqHW54i2+vyi08
    vj0LG3z9mMDUcoLb1oRmBaxVJa0ADxGPiDtB/iDW7TXZ/QT+G59G6M139xq1eDnNymIUW1e7O5+AmfnV
    rhRY7GcF8ck5wEJRvHwROcSZJSD6dZ4FqtASC+a2sGQvMm3LntJlYFgIbUJPBYzhAh+jeELkQUfLkieN
    SZE4cP7fFlNcg/1jNTm+I6Jqo8kkQFatKbWcjX5jkbwjvfPQBj2QGCGLugWJpz9E+q1YMtXcy35uJF8k
    TApbkTtkAhksPRs4ojZsWiCzs5yZFKMsLFKvU2PVnqyBpe4m7w9uyHhnc8Y7tYxvtnBVc134gYYqkZYs
    yNe0N1pENQ39UGv2IPfl2/Oz07e/EM34AxRUWiQODLtU4GOQYHUGwwdzi/26fnxGPAszUR/dkSHfydNV
    xGXwQp4NbvRjbmID+RarajMtGHilyyll1srjkXqQHFzuqSOTylwL+sBmuit4iXkGgiQNpsw85k2NUnIq
    FBb1WY2XT1ljo/yg2tR70NgIK5b3PJo727tOajbl7xEY5cND1axq2U0XJz08ICHed5pJkv4ENisSKqL4
    dm2h/UrXoi+m+fh7hWxHLX+j8EC/JpT9BCWZtXp/BdZfr7V85XbFoqiTNXoj38MN7PEAvEUkRkBhUOyq
    PglawG67oMrwt1/EXCZVr1mlHyTUKVadHqowqF9tzjv1yl85PZcN+GbOOoezm5jCmv4g+41R6bdZIUky
    x/Qded2bPp2KD8meaCBkW2aAsoA49/7OWD8HWj4V2mor35pZnps9ilI4rf7MVBr6IHJJcTO+3KyLEYzY
    4bpuvYU/ihNgIl6/Bn/3QKZJ64hng4xsW9lsSqIsmMWS5DXlUsauxZK9aJ7kOJl7wVe1Ifj5jlQzrZc/
    o0ZO8kkRZmjBOG8Yud91r/s7z4Kx4RvK+mKw5l5kSxdxAnPJ/accydfcf8nxL2Vno7gcZAAA
  path: /run/scripts/setup_sap.sh
  owner: root:root
  permissions: "0755"
  append: false

runcmd:
  - [bash, "/run/scripts/setup_sap.sh"]
